# Generated by Django 3.2.5 on 2022-03-11 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='public',
            fields=[
                ('name', models.CharField(default='si', max_length=500)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50)),
                ('nid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('nid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_marriage',
            fields=[
                ('registration_num', models.IntegerField(primary_key=True, serialize=False)),
                ('groom_name', models.CharField(max_length=200)),
                ('bride_name', models.CharField(max_length=200)),
                ('marriage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('marriage_fee', models.FloatField()),
                ('bride_nid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b_nid', to='mainapp.public')),
                ('groom_nid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='g_nid', to='mainapp.public')),
            ],
        ),
    ]
